# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature

pool:
  name: default
  demands:
  - Agent.Name -equals ip-172-31-14-139
variables:
- group: var-group

stages:
  - stage:
    jobs:
    - job: Build_Npm
      steps: 
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '14.x'
          checkLatest: true
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: "Install Dependency"
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
        displayName: "Build Created"

    - deployment: Linux_Dep
      dependsOn: Build_Npm
      environment: env
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  sudo apt install docker.io -y && systemctl start docker
                  sudo docker build -t $(docker_image):$(Build.BuildId) .
                  sudo docker run -d -p 3000:3000 $(docker_image):$(Build.BuildId) --name $(docker_cont)
                displayName: "Docker Deploy"
