apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    name: nodeapp
spec:
  containers:
  - name: nodeapp
    image: akash5791/nodeapp:tagVersion
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9090
  type: LoadBalancer
